name: alvaro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/google_ml_kit/
  google_ml_kit: 0.12.0
  # https://pub.dev/packages/camera/
  camera: 0.10.0
  # https://pub.dev/packages/image_picker
  image_picker: 0.8.5+3
  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true