name: alvaro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/google_ml_kit/
  #  google_ml_kit: 0.12.0
  # https://pub.dev/packages/camera/
  camera: 0.10.0
  # https://pub.dev/packages/image_picker
  image_picker: 0.8.5+3
  # https://pub.dev/packages/google_mlkit_text_recognition/
  google_mlkit_text_recognition: 0.4.0
  cupertino_icons: 1.0.2
  flutter_vision:
    path: ../flutter_vision
  image: ^3.2.2
  path: ^1.8.2
  path_provider: ^2.0.11
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/